kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: group-sync-operator
  labels:
    {{- include "group-sync-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: group-sync-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: group-sync-operator
  apiGroup: rbac.authorization.k8s.io
