apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: group-sync-operator
  labels:
    {{- include "group-sync-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - user.openshift.io
    resources:
      - groups
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - redhatcop.redhat.io
    resources:
      - groupsyncs
      - groupsyncs/status
      - groupsyncs/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
