# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: group-sync-operator
  name: controller-manager-metrics-monitor
  namespace: system
spec:
  endpoints:
    - authorization:
        type: Bearer
        credentials:
          key: token
          name: controller-manager-metrics-token
      interval: 30s
      port: https
      scheme: https
      tlsConfig:
        ca: 
          secret:
            key: 'tls.crt'
            name: group-sync-operator-certs
            optional: false
        serverName: controller-manager-metrics-service.system.svc
  selector:
    matchLabels:
      control-plane: group-sync-operator
