apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: controller-manager-metrics-token
  namespace: system
  annotations:
    kubernetes.io/service-account.name: controller-manager-metrics
