# Adds namespace to all resources.
namespace: release-namespace

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: group-sync-operator-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

bases:
  - ../rbac
  - ../prometheus

vars:
  - name: METRICS_SERVICE_NAME
    objref:
      kind: Service
      version: v1
      name: controller-manager-metrics-service
  - name: METRICS_SERVICE_NAMESPACE
    objref:
      kind: Service
      version: v1
      name: controller-manager-metrics-service
    fieldref:
      fieldpath: metadata.namespace
  - name: ROLE_NAME
    objref:
      kind: Role
      apiVersion: rbac.authorization.k8s.io/v1
      name: prometheus-k8s
