name: group-sync-operator
on: [push, pull_request]
jobs:
  build_test_push:
    name: "Build Test and Push"
    runs-on: ubuntu-latest
    steps:
      - name: Go Configuration
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build Operator
        run: make
      - name: Golang Test
        run: make test
      - name: "Build and Push Image"
        uses: docker/build-push-action@v1
        with:
          dockerfile: build/Dockerfile
          username: ${{ secrets.OPERATOR_REGISTRY_USERNAME }}
          password: ${{ secrets.OPERATOR_REGISTRY_PASSWORD }}
          registry: ${{ secrets.OPERATOR_REGISTRY_SERVER }}
          repository: ${{ secrets.OPERATOR_REGISTRY_REPOSITORY }}
          push: ${{ github.ref == 'refs/heads/master' && secrets.OPERATOR_REGISTRY_PUSH == 'true'  }}
          tags: latest
